### ISSUE TITLE
貌似我在Activity中的底部导航栏无法响应到中间Fragment中Recyclerview的滑动事件，

### ISSUE THREAD

**Issue by NickHu150** [Lauzy/LBehavior#1]
是不是这两个互动的view必须要在一个viewgroup中，隔了一层Fragment就不管用了

**Comment by Lauzy** [comment]
demo中写的有这种例子，可以实现的，要不然把你具体代码贴出来看看

**Comment by NickHu150** [comment]
我就是用你这个在gradle中引用了，然后就在view中的layout_behavior加了一个Bottom的那个属性，完全没反应。对了，我这个中间隔了两层Fragment。我的是Activity-Fragment-Fragment-RecyclerView，因为我普通的FAB也无法响应到滑动事件，用你这个代码貌似也响应不到

**Comment by Lauzy** [comment]
activity的根布局是CoordinatorLayout吗

**Comment by NickHu150** [comment]
是的，不然根本没发使用Behavior，我们在其他页面也用了behavior，但是只限于View和RecyclerView在同一个布局里面才可以

**Comment by Lauzy** [comment]
理论上不应该的，因为recyclerView拦截了滑动事件后触发的动画，我项目中和demo写的都是用在activity+fragment中，还用到了activity+fragment +viewpager中的fragment+recyclerView。动画触发都是正常的，你再检查下吧，可能哪里的事件被拦截了

**Comment by NickHu150** [comment]
可是当前页面都是好的，能被谁拦截了呢，你fragment是通过layout  replace的么

**Comment by Lauzy** [comment]
```java 
<android.support.design.widget.CoordinatorLayout
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
android:background="@color/color_bg_white"
android:layout_width="match_parent"
android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/main_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"/>

    <include
        layout="@layout/layout_toolbar"/>

    <android.support.design.widget.BottomNavigationView
        ......
        app:layout_behavior="@string/bottom_view_behavior"/>

    <android.support.design.widget.FloatingActionButton
        ......
        app:layout_behavior="@string/fab_vertical_behavior"/>
</android.support.design.widget.CoordinatorLayout>

```

我的布局是这样的，fragment 就是正常的写法，getSupportFragmentManager().beginTransaction(). .add(R.id.main_frame, mMineFragment);

**Comment by NickHu150** [comment]
好，那我自己先看看吧，有啥问题再过来请教

**Comment by Lauzy** [comment]
好的，我刚刚自己又测了一下，可以触发的。
