### ISSUE TITLE
RecyclerView.smoothScrollToPosition（0）

### ISSUE THREAD

**Issue by ZcChang** [Lauzy/LBehavior#3]
用RecyclerView.smoothScrollToPosition（0）;到顶端之后，隐藏的标题会显示不出来 应该怎么办？

**Comment by Lauzy** [comment]
简书里也是你问的吧，这种需求主动调用一下 show() 吧

**Comment by zhengtianle** [comment]
怎么把底部的导航栏点击动画覆盖呢？

**Comment by Lauzy** [comment]
@zhengtianle  指的是 BottomNavigationView 的动画吗，官方没提供的取消动画的方法，建议用其他控件替代或者自定义一个。
